### ISSUE TITLE
Expose ShrinkWrapp property from ListView.Builder

### ISSUE THREAD

**Issue by akdu12** [sooxie/list_treeview#2]
Hey
good job on building this package
I have  a use case where i need to set shrinkWrap property of ListView.the only thing i can do is to copy the file to my project and edit but it would be awesome to allow users to do so easly.

Kind regards!

**Comment by sooxie** [comment]
It is a good idea. I have added the functionality you mentioned, such as shrinkWrap padding and reverse.
