### ISSUE TITLE
Expose notifyListeners in TreeViewController 

### ISSUE THREAD

**Issue by archie-sh** [sooxie/list_treeview#3]
Hi, 

thanks for writing the plugin, it works quite well.

We came across the situation in which we need to udpate NodeData we have extended while using the same TreeViewController to keep nodes expanded / collapsed after the update. 

I considered writing methods to update the node and implemented them in this fork https://github.com/archie-sh/list_treeview but its nicer to apply the logic on the custom objects on our app side and just notifying the tree that there has been a change. 

I would suggest expsoing notifiyListeneres in a rebuild method. e.g. 

`  void rebuild() {
    notifyListeners();
  }`

Regards.

**Comment by sooxie** [comment]
I am very sorry that I have been too busy to reply to you recently. I think your idea is good. Thank you
