### ISSUE TITLE
初始化数据的时候能否定义节点的展开属性呢？

### ISSUE THREAD

**Issue by justdoitgo** [sooxie/list_treeview#8]
比如
  TreeNodeData({this.label, this.id,this.oid, bool mesExpand = false}){
    print('mesExpand = ${mesExpand}');
    super.isExpand=mesExpand;
  }

**Comment by justdoitgo** [comment]
是否有方法可以获取所有选中的节点呢？

**Comment by sooxie** [comment]
/// Select itself and all child nodes
_controller.selectAllChild(item);

用这个方法就可以
