### ISSUE TITLE
Content of Node is not refreshing

### ISSUE THREAD

**Issue by ynnob** [sooxie/list_treeview#9]
Hey,

we use BloC to handle our state of the View. After a navigation event and returning to the view that contains the ListTreeView i reload the Data that is displayed by the ListTreeView.

If i set the treeData() a second time, the itemBuilder of the ListTreeView uses the old data of the initial TreeData() call.

How can i force the ListTreeView to reload the Data so changes are displayed?
In my example i have an item with an int value that is display in the ListTreeView. Inside the itemBuilder i do something like this:

```
treeViewController.treeData(lChecklistNodeData);
return ListTreeView(
      controller: treeViewController,
      itemBuilder: (BuildContext context, NodeData data) {
        ChecklistNodeData item = data as ChecklistNodeData;

return Text('${item.intValue}');
});

```

As i said this is working fine the first time, but when i reload the data and the build() method is retriggered the Data in the itemBuilder function is not refreshed. I checked the data i pass to treeData() and it is definitly the new data. But still the itemBuilder uses the data of the first set of treeData().

I managed to refresh the Parent items by resetting the TreeViewController
`treeViewController = new TreeViewController();`

but this leads to only the parents showing up. All child elements are missing after the second rebuild if i do this.

Thanks in advance

**Comment by sooxie** [comment]
Ok, I will try the situation you said, please wait a moment.

**Comment by sooxie** [comment]
Hi buddy, now you can refresh the data with _controller.rebuild(). I'll make it easier to refresh the data and fix it when I have time.

**Comment by ynnob** [comment]
> Hi buddy, now you can refresh the data with _controller.rebuild(). I'll make it easier to refresh the data and fix it when I have time.

Thanks for your response! Could you reproduce the issue?
I will give it a try on Monday and I will let you know if it worked.

Thanks

**Comment by ynnob** [comment]
> Hi buddy, now you can refresh the data with _controller.rebuild(). I'll make it easier to refresh the data and fix it when I have time.

Hey you did not update the extension. There is no new version.
If i use _controller.rebuild() nothing happens. The Values of the TreeView still do not update.

**Comment by dipen-apptrait** [comment]
Hey, have you found any solution for content refreshing?

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by ynnob** [comment]
> Hey, have you found any solution for content refreshing?

Nope. Still no solution.

**Comment by dipen-apptrait** [comment]
Hey! I got the solution for a content refresh.
 _controller!.dispose();
 _controller = TreeViewController();
// -- Call function to fetch updated data

 setState(() {
 _controller!.rebuild();
 });

**Comment by sooxie** [comment]
@Bonnyfication   You can use this function

_controller!.rebuild();

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
